Add encoding to definitions
Nostest where also failing due to encoding problems, see below:

    E..
    ======================================================================
    ERROR: Failure: SyntaxError (Non-ASCII character '\xc2' in file
    /Users/pjn/dev/HA-Spixy/spixy/irc/definitions.py on line 4, but no
    encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    (definitions.py, line 4))
    ----------------------------------------------------------------------